project:
  type: book
book:
  title: The Role of Warmth and Competence Perceptions in Labor Market Outcomes
  date: today
  date-format: long
  author:
    - name: Carina Hausladen
      orcid: 0000-0003-4397-2339
      affiliations: Caltech
    - name: Marcos Gallo
      affiliations: Caltech
  chapters:
    - index.qmd
    - names.qmd
    - categories.qmd
   # - datasets.qmd
   # - appendix.qmd
   # - references.qmd
license: CC BY
format:
  html:
    embed-resources: true
    theme: cosmo
editor: source
citation:
  type: article
  citation-key: citationKeyNumber
  status: draft
execute:
  cache: true
  echo: false
  warning: false
  message: false